### ISSUE TITLE
Replace deprecated list_queue with new list_match plugin

### ISSUE THREAD

**Issue by cgiacofei** [cgiacofei/flexget#11]
Need to make sure entries are being properly removed from lists (both flexget lists and trakt).
list_interface plugins need to be updated in movie queue tasks and movie templates.

list_queue becomes list_match

```
list_match:
  from:
    - <list_type>: <list_name>
  action: [*accept*|reject]
  remove_on_match: [*yes*|no]
  single_match: [*yes*|no]
```
