### ISSUE TITLE
Use identified_by to set series numbering?

### ISSUE THREAD

**Issue by cgiacofei** [cgiacofei/flexget#12]
In download_tv and download_kids_tv tasks replace `begine: S01E01` with `identified_by: ep`

[Flexget Documentation](http://flexget.com/Plugins/series/identified_by)

```
configure_series:
  from:
    trakt_list:
      username: test
      password: test
      list: watchlist
      type: shows
      strip_dates: yes
    listdir:
      - "/media/completed/TV Shows"
  settings:
    identified_by: ep
```
