### ISSUE TITLE
Use new list interface for multiple movie queues

### ISSUE THREAD

**Issue by cgiacofei** [cgiacofei/flexget#4]
### New Interface

http://flexget.com/wiki/Plugins/List

`list_add` plugin adds movies from trakt watchlist to the specified list.
### Sample Code

``` YAML
populate_queue:
  trakt_list:
    username: traktusername
    list: watchlist
    type: movies 
  accept_all: yes
  list_add:
    - movie_list: my_list

download_task:
  rss: http://url.com/feed.xml
  quality: 720p
  list_queue:
    - movie_list: my_list
  download: /path/to/download
```
